### ISSUE TITLE
Vocabulary size

### ISSUE THREAD

**Issue by mitramir55** [khashei/bolbolzaban-gpt2-persian#2]
Hi,

Firstly, thank you Mr. @khashei for this amazing model and your efforts in Persian NLP.

I'm here to report an error I get when trying to use this model for Masked Language Modeling. This error seems to be related to the config of the model, specifically, the vocabulary size.

My goal is to give the model a sequence of words with masked tokens in between and then predict these masks and output the most probable tokens that can substitute the missing values. Here is my code:
``` # importing the model

model_bolbol_path = "bolbolzaban/gpt2-persian"
model_bol = TFAutoModelWithLMHead.from_pretrained(model_bolbol_path)
tokenizer_bol = AutoTokenizer.from_pretrained(model_bolbol_path)

# defining a sequence
sequence_fa = f"من به [MSK] رفتم تا درس بخوانم."

# encode the sequence
input_fa = tokenizer_bol.encode(sequence_fa, return_tensors="tf")

# give it to model to get the logits
token_logits = model_bol(input_fa)[0]
```
After executing the last line of code in the aforementioned block, I get the following error:
```InvalidArgumentError: indices[0,6] = 25000 is not in [0, 25000) [Op:ResourceGather]```

I assume I have to change the vocabulary size in the config? or am I missing something?

Thanks in advance,
Mitra

**Comment by khashei** [comment]
This is because HF AutoTokenizer makes some changes in the vocab. Seems like [MSK] was added to the vocab but somewhere in the model the vocab size is not updated accordingly:
```
tokenizer = AutoTokenizer.from_pretrained('bolbolzaban/gpt2-persian')
print(tokenizer.get_added_vocab())
```
You can use [MASK] which is already a reserved token in the vocab:
```
tokenizer = AutoTokenizer.from_pretrained('bolbolzaban/gpt2-persian')
print(tokenizer.tokenize('در یک [MASK] شگفت انگیز، پژوهشگران'))
```
You can also use any of the reserved tokens in the vocab ([RES3], [RES4], ...[RES16]) and give your meaning to that during your training process:
```
tokenizer = AutoTokenizer.from_pretrained('bolbolzaban/gpt2-persian')
print(tokenizer.tokenize('در یک [RES10] شگفت انگیز، پژوهشگران'))
```
Please note that none of the above tokens ([MSK], [MASK], [RES3],...[RES16]) were used in GPT2 pre-training. As an auto-regressive language model mask filling is not the expertise of GPT2. You may want to try one of the BERT models for this use case.
